version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  mongo:
    image: mongo

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management 

  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: Services/Web/WebMVC/Dockerfile

  transportation.api:
    image: ${DOCKER_REGISTRY-}transportationapi
    build:
      context: .
      dockerfile: Services/Transportation/Transport.API/Transport.API/Dockerfile


  routing.api:
    image: ${DOCKER_REGISTRY-}routingapi
    build:
      context: .
      dockerfile: Services/Routing/Routing.API/Dockerfile


  cargo.api:
    image: ${DOCKER_REGISTRY-}cargoapi
    build:
      context: .
      dockerfile: Services/Cargo/Cargo.API/Dockerfile

