version: '3.4'

services:

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=qwerty@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5433:1433"
    expose:
      - "1433"
    volumes:
      - mssql:/var/opt/mssql

  postgres:
    container_name: postgres
    environment:
      - POSTGRES_DB=CargoAccountDB
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=12345678
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "7432:5432"
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

  mongo:
    container_name: mongo
    ports:
      - "27018:27017"
    expose:
      - "27017"
    volumes:
      - mongo:/data/db

  redis:
    container_name: redis
    ports:
      - "6380:6379"
    expose:
      - "6379"
    volumes:
      - redis:/data

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "15672:15672"
    expose:
      - "5672"
    
  cargo.api:
    container_name: cargo
    hostname: cargo
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mssql
      - rabbitmq
      - redis

  routing.api:
    container_name: routing
    hostname: routing
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo
      - rabbitmq
      - redis

  transportation.api:
    container_name: transportation
    hostname: transportation
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo
      - redis

  account.api:
    container_name: account
    hostname: account
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgres

  apigateway:
    container_name: ocelot
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - cargo.api
      - transportation.api
      - routing.api
      - account.api

  webmvc:
    container_name: webmvc
    hostname: webmvc
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
      #
      # Old version.
      #
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=7242
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=qwerty@123 #<-- So this isn't a good idea in your real project.
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webmvc_c.pfx
    #ports:
      #- "7242:443" #<-- Project endpoint: https://localhost:7242/account/index.
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
    depends_on:
      - apigateway

  nginx:
    container_name: nginx
    ports:
      - "5090:80"
    volumes:
      - ./ApiGateway/Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webmvc


volumes:
  mssql:
    external: false
  postgres:
    external: false
  mongo:
    external: false
  redis:
    external: false
