version: '3.4'

services:

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=qwerty@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5433:1433"
    expose:
      - "1433"
    volumes:
      - mssql:/var/opt/mssql

  mongo:
    container_name: mongo
    ports:
      - "27018:27017"
    expose:
      - "27017"
    volumes:
      - mongo:/data/db

  redis:
    container_name: redis
    ports:
      - "6380:6379"
    expose:
      - "6379"
    volumes:
      - redis:/data

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "15672:15672"
    expose:
      - "5672"
    
  cargo.api:
    container_name: cargo
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mssql
      - rabbitmq
      - redis

  routing.api:
    container_name: routing
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo
      - rabbitmq
      - redis

  transportation.api:
    container_name: transportation
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo
      - redis

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7242
      - ASPNETCORE_Kestrel__Certificates__Default__Password=qwerty@123 #<-- So this isn't a good idea in your real project.
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webmvc_c.pfx
    ports:
      - "5080:80"
      - "7242:443" #<-- Project endpoint.
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
    depends_on:
      - mongo

volumes:
  mssql:
    external: false
  mongo:
    external: false
  redis:
    external: false