version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  postgres:
    image: postgres

  mongo:
    image: mongo

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management 
  
  nginx:
    image: nginx
  
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile

  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile

  transportation.api:
    image: ${DOCKER_REGISTRY-}transportationapi
    build:
      context: .
      dockerfile: Services/Transportation/Transport.API/Transport.API/Dockerfile

  routing.api:
    image: ${DOCKER_REGISTRY-}routingapi
    build:
      context: .
      dockerfile: Services/Routing/Routing.API/Dockerfile

  cargo.api:
    image: ${DOCKER_REGISTRY-}cargoapi
    build:
      context: .
      dockerfile: Services/Cargo/Cargo.API/Dockerfile

  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Account/Account.API/Dockerfile

